sudo: required
services:
  - docker

before_install:
  - docker build -t innervision/docker-react-dev -f Dockerfile.dev .

script:
  - docker run innervision/docker-react-dev npm run test -- --coverage