sudo: required
services:
  - docker

before_install:
  - docker build -t innervision/docker-react-dev -f Dockerfile.dev .

script:
  - docker run innervision/docker-react-dev npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-782071332860"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
